/**
 * Australian Skilled Occupation Lists — Verified 2025
 *
 * SOURCES:
 *  • immi.homeaffairs.gov.au/visas/working-in-australia/skill-occupation-list
 *  • anzscosearch.com/mltssl  (MLTSSL — 212 occupations)
 *  • anzscosearch.com/csol   (CSOL — 456 occupations, eff. 7 Dec 2024)
 *  • ANZSCO official codes verified against ABS classification
 *
 * LIST MEANINGS:
 *  MLTSSL = Medium and Long-Term Strategic Skills List (212 occupations)
 *           → Subclass 189 (points-tested, no sponsorship), 190, 491, 485, 186, 482/SID
 *  STSOL  = Short-Term Skilled Occupation List (215 occupations)
 *           → Subclass 190, 491 ONLY — NOT 189
 *  ROL    = Regional Occupation List (77 occupations)
 *           → Subclass 491, 494 ONLY — regional visas only
 *  CSOL   = Core Skills Occupation List (456 occupations, from 7 Dec 2024)
 *           → Skills in Demand (SID) visa (replaced 482 TSS from 7 Dec 2024) + 186 Direct Entry
 *           → CSOL is broader than MLTSSL and includes ALL MLTSSL occupations + many more
 *
 * KEY 2024-25 CHANGE:
 *  The Skills in Demand (SID) visa (Subclass 482) replaced the TSS visa from 7 December 2024.
 *  Two streams: Core Skills (CSOL occupations, salary AUD $76,515–$141,210)
 *               Specialist Skills (no occupation list required, salary ≥ AUD $141,210)
 *
 * ANZSCO NOTE:
 *  OSCA (Occupation Standard Classification for Australia) officially replaced ANZSCO
 *  from 6 December 2024 for new classifications, but ANZSCO codes remain in use for
 *  all current visa applications.
 */

export type OccupationList = "MLTSSL" | "STSOL" | "ROL" | "CSOL";
export type SkillLevel = 1 | 2 | 3;

export interface Occupation {
  anzsco: string;
  title: string;
  skillLevel: SkillLevel;
  category: string;
  lists: OccupationList[];
  /** Visa subclasses this occupation can access for skilled migration */
  visaAccess: string[];
  medianSalary: string;
  assessingBody: string;
  notes?: string;
}

export const occupations: Occupation[] = [

  // ── ICT & TECHNOLOGY (MLTSSL — verified) ─────────────────────────────────
  {
    anzsco: "135111",
    title: "Chief Information Officer",
    skillLevel: 1,
    category: "ICT & Technology",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $185,000–$280,000",
    assessingBody: "ACS (Australian Computer Society)",
  },
  {
    anzsco: "261111",
    title: "ICT Business Analyst",
    skillLevel: 1,
    category: "ICT & Technology",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $110,000–$145,000",
    assessingBody: "ACS (Australian Computer Society)",
    notes: "One of the highest volume PR categories nationally (~4,200 grants in 2023-24)",
  },
  {
    anzsco: "261112",
    title: "Systems Analyst",
    skillLevel: 1,
    category: "ICT & Technology",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $105,000–$140,000",
    assessingBody: "ACS (Australian Computer Society)",
  },
  {
    anzsco: "261211",
    title: "Multimedia Specialist",
    skillLevel: 1,
    category: "ICT & Technology",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $80,000–$120,000",
    assessingBody: "ACS (Australian Computer Society)",
  },
  {
    anzsco: "261212",
    title: "Web Developer",
    skillLevel: 1,
    category: "ICT & Technology",
    lists: ["STSOL", "CSOL"],
    visaAccess: ["190", "491", "482-SID"],
    medianSalary: "AUD $90,000–$130,000",
    assessingBody: "ACS (Australian Computer Society)",
    notes: "STSOL (not MLTSSL) — cannot access Subclass 189 independently. CSOL eligible for employer-sponsored SID visa.",
  },
  {
    anzsco: "261311",
    title: "Analyst Programmer",
    skillLevel: 1,
    category: "ICT & Technology",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $110,000–$150,000",
    assessingBody: "ACS (Australian Computer Society)",
  },
  {
    anzsco: "261312",
    title: "Developer Programmer",
    skillLevel: 1,
    category: "ICT & Technology",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $110,000–$155,000",
    assessingBody: "ACS (Australian Computer Society)",
  },
  {
    anzsco: "261313",
    title: "Software Engineer",
    skillLevel: 1,
    category: "ICT & Technology",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $115,000–$165,000",
    assessingBody: "ACS (Australian Computer Society)",
    notes: "~1,120 PR grants in NSW alone in 2024–25. Top 189 occupation. 189 cutoff 80–95 points.",
  },
  {
    anzsco: "261399",
    title: "Software and Applications Programmers nec",
    skillLevel: 1,
    category: "ICT & Technology",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $100,000–$145,000",
    assessingBody: "ACS (Australian Computer Society)",
    notes: "NEC (not elsewhere classified) — catches newer roles like Data Engineer, DevOps, Cloud Engineer where no specific ANZSCO code applies",
  },
  {
    anzsco: "262111",
    title: "Database Administrator",
    skillLevel: 1,
    category: "ICT & Technology",
    lists: ["STSOL", "CSOL"],
    visaAccess: ["190", "491", "482-SID"],
    medianSalary: "AUD $105,000–$145,000",
    assessingBody: "ACS (Australian Computer Society)",
    notes: "STSOL — not eligible for Subclass 189. Access 190 (state nomination) or 491 (regional) for PR pathway.",
  },
  {
    anzsco: "262112",
    title: "ICT Security Specialist",
    skillLevel: 1,
    category: "ICT & Technology",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $115,000–$170,000",
    assessingBody: "ACS (Australian Computer Society)",
    notes: "MLTSSL — Cyber security roles in very high demand. 189 access with sufficient points.",
  },
  {
    anzsco: "263111",
    title: "Computer Network and Systems Engineer",
    skillLevel: 1,
    category: "ICT & Technology",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $110,000–$155,000",
    assessingBody: "ACS (Australian Computer Society)",
  },
  {
    anzsco: "263311",
    title: "Telecommunications Engineer",
    skillLevel: 1,
    category: "ICT & Technology",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $105,000–$145,000",
    assessingBody: "Engineers Australia",
  },
  {
    anzsco: "263312",
    title: "Telecommunications Network Engineer",
    skillLevel: 1,
    category: "ICT & Technology",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $100,000–$140,000",
    assessingBody: "Engineers Australia",
  },
  // New CSOL-only cyber roles (employer-sponsored SID visa only — not on MLTSSL)
  {
    anzsco: "262113",
    title: "Systems Administrator",
    skillLevel: 1,
    category: "ICT & Technology",
    lists: ["CSOL"],
    visaAccess: ["482-SID", "186"],
    medianSalary: "AUD $95,000–$130,000",
    assessingBody: "ACS (Australian Computer Society)",
    notes: "CSOL only (employer-sponsored). Not on MLTSSL — cannot access Subclass 189/190/491 independently.",
  },
  {
    anzsco: "224115",
    title: "Data Scientist",
    skillLevel: 1,
    category: "ICT & Technology",
    lists: ["CSOL"],
    visaAccess: ["482-SID", "186"],
    medianSalary: "AUD $115,000–$165,000",
    assessingBody: "ACS (Australian Computer Society)",
    notes: "CSOL only. ANZSCO 224115 (not a 261xxx code). Employer-sponsored SID/186 only. For points-tested visas, assess under 261399 NEC with ACS.",
  },
  {
    anzsco: "224114",
    title: "Data Analyst",
    skillLevel: 1,
    category: "ICT & Technology",
    lists: ["CSOL"],
    visaAccess: ["482-SID", "186"],
    medianSalary: "AUD $90,000–$130,000",
    assessingBody: "ACS (Australian Computer Society)",
    notes: "CSOL only. May be assessed under 261111 ICT Business Analyst or 261399 NEC for points-tested visas.",
  },

  // ── ENGINEERING (MLTSSL — all verified) ──────────────────────────────────
  {
    anzsco: "233111",
    title: "Chemical Engineer",
    skillLevel: 1,
    category: "Engineering",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $110,000–$155,000",
    assessingBody: "Engineers Australia",
  },
  {
    anzsco: "233112",
    title: "Materials Engineer",
    skillLevel: 1,
    category: "Engineering",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $105,000–$145,000",
    assessingBody: "Engineers Australia",
  },
  {
    anzsco: "233211",
    title: "Civil Engineer",
    skillLevel: 1,
    category: "Engineering",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $105,000–$150,000",
    assessingBody: "Engineers Australia",
    notes: "High demand across infrastructure projects in all states",
  },
  {
    anzsco: "233212",
    title: "Geotechnical Engineer",
    skillLevel: 1,
    category: "Engineering",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $110,000–$155,000",
    assessingBody: "Engineers Australia",
  },
  {
    anzsco: "233213",
    title: "Quantity Surveyor",
    skillLevel: 1,
    category: "Engineering",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $100,000–$150,000",
    assessingBody: "AIQS (Australian Institute of Quantity Surveyors)",
    notes: "ANZSCO 233213. Assessing body is AIQS — not Engineers Australia",
  },
  {
    anzsco: "233214",
    title: "Structural Engineer",
    skillLevel: 1,
    category: "Engineering",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $110,000–$155,000",
    assessingBody: "Engineers Australia",
  },
  {
    anzsco: "233215",
    title: "Transport Engineer",
    skillLevel: 1,
    category: "Engineering",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $105,000–$150,000",
    assessingBody: "Engineers Australia",
  },
  {
    anzsco: "233311",
    title: "Electrical Engineer",
    skillLevel: 1,
    category: "Engineering",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $110,000–$160,000",
    assessingBody: "Engineers Australia",
  },
  {
    anzsco: "233411",
    title: "Electronics Engineer",
    skillLevel: 1,
    category: "Engineering",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $105,000–$145,000",
    assessingBody: "Engineers Australia",
  },
  {
    anzsco: "233511",
    title: "Industrial Engineer",
    skillLevel: 1,
    category: "Engineering",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $105,000–$145,000",
    assessingBody: "Engineers Australia",
  },
  {
    anzsco: "233512",
    title: "Mechanical Engineer",
    skillLevel: 1,
    category: "Engineering",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $105,000–$150,000",
    assessingBody: "Engineers Australia",
  },
  {
    anzsco: "233513",
    title: "Production or Plant Engineer",
    skillLevel: 1,
    category: "Engineering",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $105,000–$148,000",
    assessingBody: "Engineers Australia",
  },
  {
    anzsco: "233611",
    title: "Mining Engineer (excl. Petroleum)",
    skillLevel: 1,
    category: "Engineering",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $130,000–$200,000",
    assessingBody: "Engineers Australia",
    notes: "Extremely high demand in WA and QLD. Consistently among highest salaries for engineers.",
  },
  {
    anzsco: "233612",
    title: "Petroleum Engineer",
    skillLevel: 1,
    category: "Engineering",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $140,000–$210,000",
    assessingBody: "Engineers Australia",
  },
  {
    anzsco: "233911",
    title: "Aeronautical Engineer",
    skillLevel: 1,
    category: "Engineering",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $110,000–$160,000",
    assessingBody: "Engineers Australia",
  },
  {
    anzsco: "233913",
    title: "Biomedical Engineer",
    skillLevel: 1,
    category: "Engineering",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $100,000–$145,000",
    assessingBody: "Engineers Australia",
  },
  {
    anzsco: "233915",
    title: "Environmental Engineer",
    skillLevel: 1,
    category: "Engineering",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $100,000–$145,000",
    assessingBody: "Engineers Australia",
  },
  {
    anzsco: "233916",
    title: "Naval Architect / Marine Designer",
    skillLevel: 1,
    category: "Engineering",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $100,000–$150,000",
    assessingBody: "Engineers Australia",
  },
  {
    anzsco: "133111",
    title: "Construction Project Manager",
    skillLevel: 1,
    category: "Engineering",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $130,000–$200,000",
    assessingBody: "VETASSESS",
    notes: "Very high demand across major infrastructure projects nationally",
  },

  // ── HEALTHCARE — MEDICAL PRACTITIONERS (MLTSSL — all verified) ────────────
  {
    anzsco: "253111",
    title: "General Medical Practitioner (GP)",
    skillLevel: 1,
    category: "Healthcare — Doctors",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $200,000–$350,000",
    assessingBody: "Medical Board of Australia (via AMC)",
    notes: "Chronic shortage, especially in regional areas. Exempt from 45-year age limit for 186 ENS. Priority processing under MD105.",
  },
  {
    anzsco: "253311",
    title: "Specialist Physician (General Medicine)",
    skillLevel: 1,
    category: "Healthcare — Doctors",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $300,000–$550,000",
    assessingBody: "Medical Board of Australia (via AMC)",
  },
  {
    anzsco: "253312",
    title: "Cardiologist",
    skillLevel: 1,
    category: "Healthcare — Doctors",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $400,000–$700,000",
    assessingBody: "Medical Board of Australia (via AMC)",
    notes: "Exempt from age limit for 186 ENS",
  },
  {
    anzsco: "253314",
    title: "Medical Oncologist",
    skillLevel: 1,
    category: "Healthcare — Doctors",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $350,000–$600,000",
    assessingBody: "Medical Board of Australia (via AMC)",
  },
  {
    anzsco: "253317",
    title: "Intensive Care Specialist",
    skillLevel: 1,
    category: "Healthcare — Doctors",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $400,000–$650,000",
    assessingBody: "Medical Board of Australia (via AMC)",
  },
  {
    anzsco: "253321",
    title: "Paediatrician",
    skillLevel: 1,
    category: "Healthcare — Doctors",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $350,000–$600,000",
    assessingBody: "Medical Board of Australia (via AMC)",
  },
  {
    anzsco: "253411",
    title: "Psychiatrist",
    skillLevel: 1,
    category: "Healthcare — Doctors",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $350,000–$600,000",
    assessingBody: "Medical Board of Australia (via AMC)",
    notes: "Critical shortage nationally. Priority processing under Ministerial Direction 105.",
  },
  {
    anzsco: "253511",
    title: "Surgeon (General)",
    skillLevel: 1,
    category: "Healthcare — Doctors",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $400,000–$700,000+",
    assessingBody: "Medical Board of Australia (via AMC)",
    notes: "Includes 253512 Cardiothoracic, 253513 Neurosurgeon, 253514 Orthopaedic, 253515 ENT, 253518 Urologist — all MLTSSL",
  },
  {
    anzsco: "253912",
    title: "Emergency Medicine Specialist",
    skillLevel: 1,
    category: "Healthcare — Doctors",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $350,000–$550,000",
    assessingBody: "Medical Board of Australia (via AMC)",
  },
  {
    anzsco: "253913",
    title: "Obstetrician and Gynaecologist",
    skillLevel: 1,
    category: "Healthcare — Doctors",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $400,000–$650,000",
    assessingBody: "Medical Board of Australia (via AMC)",
  },
  {
    anzsco: "253917",
    title: "Diagnostic and Interventional Radiologist",
    skillLevel: 1,
    category: "Healthcare — Doctors",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $400,000–$700,000",
    assessingBody: "Medical Board of Australia (via AMC)",
  },

  // ── HEALTHCARE — NURSING (MLTSSL — all verified with correct ANZSCO codes) ─
  {
    anzsco: "254111",
    title: "Midwife",
    skillLevel: 1,
    category: "Healthcare — Nursing",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $80,000–$115,000",
    assessingBody: "ANMAC (Australian Nursing & Midwifery Accreditation Council)",
    notes: "ANZSCO 254111 = Midwife (not Registered Nurse). Critical shortage in all states.",
  },
  {
    anzsco: "254411",
    title: "Nurse Practitioner",
    skillLevel: 1,
    category: "Healthcare — Nursing",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $100,000–$140,000",
    assessingBody: "ANMAC (Australian Nursing & Midwifery Accreditation Council)",
    notes: "Advanced practice registered nurses with prescribing rights",
  },
  {
    anzsco: "254412",
    title: "Registered Nurse (Aged Care)",
    skillLevel: 1,
    category: "Healthcare — Nursing",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $75,000–$100,000",
    assessingBody: "ANMAC (Australian Nursing & Midwifery Accreditation Council)",
    notes: "Critical shortage. Priority processing under MD105. High demand in all states.",
  },
  {
    anzsco: "254415",
    title: "Registered Nurse (Critical Care & Emergency)",
    skillLevel: 1,
    category: "Healthcare — Nursing",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $80,000–$115,000",
    assessingBody: "ANMAC (Australian Nursing & Midwifery Accreditation Council)",
  },
  {
    anzsco: "254418",
    title: "Registered Nurse (Medical)",
    skillLevel: 1,
    category: "Healthcare — Nursing",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $75,000–$105,000",
    assessingBody: "ANMAC (Australian Nursing & Midwifery Accreditation Council)",
  },
  {
    anzsco: "254422",
    title: "Registered Nurse (Mental Health)",
    skillLevel: 1,
    category: "Healthcare — Nursing",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $78,000–$110,000",
    assessingBody: "ANMAC (Australian Nursing & Midwifery Accreditation Council)",
    notes: "Priority processing. Mental health nursing shortage is acute nationally.",
  },
  {
    anzsco: "254423",
    title: "Registered Nurse (Perioperative)",
    skillLevel: 1,
    category: "Healthcare — Nursing",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $80,000–$115,000",
    assessingBody: "ANMAC (Australian Nursing & Midwifery Accreditation Council)",
  },
  {
    anzsco: "254499",
    title: "Registered Nurses nec",
    skillLevel: 1,
    category: "Healthcare — Nursing",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $75,000–$105,000",
    assessingBody: "ANMAC (Australian Nursing & Midwifery Accreditation Council)",
    notes: "Includes 254413 Child & Family Health, 254414 Community Health, 254416 Developmental Disability, 254417 Disability & Rehab, 254421 Medical Practice, 254424 Surgical, 254425 Paediatrics",
  },

  // ── HEALTHCARE — ALLIED HEALTH (MLTSSL — verified correct ANZSCO codes) ──
  {
    anzsco: "251211",
    title: "Medical Diagnostic Radiographer",
    skillLevel: 1,
    category: "Healthcare — Allied Health",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $85,000–$120,000",
    assessingBody: "ASMIRT (Australian Society of Medical Imaging and Radiation Therapy)",
  },
  {
    anzsco: "251214",
    title: "Sonographer",
    skillLevel: 1,
    category: "Healthcare — Allied Health",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $95,000–$135,000",
    assessingBody: "ASMIRT (Australian Society of Medical Imaging and Radiation Therapy)",
    notes: "Shortage in regional areas. Very high demand.",
  },
  {
    anzsco: "251411",
    title: "Optometrist",
    skillLevel: 1,
    category: "Healthcare — Allied Health",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $90,000–$130,000",
    assessingBody: "OCANZ (Optometry Council of Australia and New Zealand)",
    notes: "ANZSCO 251411 = Optometrist. Not to be confused with 252411 (Occupational Therapist).",
  },
  {
    anzsco: "252411",
    title: "Occupational Therapist",
    skillLevel: 1,
    category: "Healthcare — Allied Health",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $80,000–$115,000",
    assessingBody: "Occupational Therapy Council of Australia (OTC)",
    notes: "ANZSCO 252411 = Occupational Therapist. High demand for NDIS support. Not 251411.",
  },
  {
    anzsco: "252511",
    title: "Physiotherapist",
    skillLevel: 1,
    category: "Healthcare — Allied Health",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $80,000–$120,000",
    assessingBody: "Australian Physiotherapy Council (APC)",
    notes: "ANZSCO 252511 = Physiotherapist. Not 251512 (which is Industrial Pharmacist).",
  },
  {
    anzsco: "252111",
    title: "Pharmacist (all streams)",
    skillLevel: 1,
    category: "Healthcare — Allied Health",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $90,000–$130,000",
    assessingBody: "Australian Pharmacy Council (APC)",
    notes: "Includes 251511 Hospital Pharmacist, 251512 Industrial, 251513 Retail — all MLTSSL. Assess under AHPRA registration.",
  },
  {
    anzsco: "252611",
    title: "Podiatrist",
    skillLevel: 1,
    category: "Healthcare — Allied Health",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $75,000–$110,000",
    assessingBody: "Podiatry Board of Australia",
  },
  {
    anzsco: "252711",
    title: "Audiologist",
    skillLevel: 1,
    category: "Healthcare — Allied Health",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $80,000–$115,000",
    assessingBody: "VETASSESS",
    notes: "ANZSCO 252711 = Audiologist. Not Psychologist (which is 272311–272399).",
  },
  {
    anzsco: "252712",
    title: "Speech Pathologist",
    skillLevel: 1,
    category: "Healthcare — Allied Health",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $80,000–$115,000",
    assessingBody: "Speech Pathology Australia (SPA)",
    notes: "High demand for NDIS and paediatric services",
  },
  {
    anzsco: "272311",
    title: "Clinical Psychologist",
    skillLevel: 1,
    category: "Healthcare — Allied Health",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $90,000–$145,000",
    assessingBody: "APS (Australian Psychological Society)",
    notes: "ANZSCO 272311–272399 for all psychologist types. Not 252711 (that's Audiologist).",
  },
  {
    anzsco: "234711",
    title: "Veterinarian",
    skillLevel: 1,
    category: "Healthcare — Allied Health",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $80,000–$140,000",
    assessingBody: "Veterinary Practitioners Registration Board (AVBC)",
    notes: "High demand in large animal practice and regional Australia",
  },
  {
    anzsco: "234611",
    title: "Medical Laboratory Scientist",
    skillLevel: 1,
    category: "Healthcare — Allied Health",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $75,000–$110,000",
    assessingBody: "AIMS (Australian Institute of Medical Scientists)",
  },

  // ── ACCOUNTING & FINANCE (MLTSSL — verified) ─────────────────────────────
  {
    anzsco: "221111",
    title: "Accountant (General)",
    skillLevel: 1,
    category: "Accounting & Finance",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $85,000–$120,000",
    assessingBody: "CPA Australia / CAANZ / IPA",
    notes: "~4,570 PR grants nationally in 2023-24 — one of highest volumes. 189 cutoff typically 80–90 points.",
  },
  {
    anzsco: "221112",
    title: "Management Accountant",
    skillLevel: 1,
    category: "Accounting & Finance",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $95,000–$135,000",
    assessingBody: "CPA Australia / CAANZ",
  },
  {
    anzsco: "221113",
    title: "Taxation Accountant",
    skillLevel: 1,
    category: "Accounting & Finance",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $90,000–$130,000",
    assessingBody: "CPA Australia / CAANZ / IPA",
  },
  {
    anzsco: "221213",
    title: "External Auditor",
    skillLevel: 1,
    category: "Accounting & Finance",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $90,000–$140,000",
    assessingBody: "CPA Australia / CAANZ",
  },
  {
    anzsco: "221214",
    title: "Internal Auditor",
    skillLevel: 1,
    category: "Accounting & Finance",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $90,000–$135,000",
    assessingBody: "VETASSESS",
  },
  {
    anzsco: "224111",
    title: "Actuary",
    skillLevel: 1,
    category: "Accounting & Finance",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $130,000–$200,000",
    assessingBody: "VETASSESS",
  },
  {
    anzsco: "132211",
    title: "Finance Manager",
    skillLevel: 1,
    category: "Accounting & Finance",
    lists: ["CSOL"],
    visaAccess: ["482-SID", "186"],
    medianSalary: "AUD $130,000–$200,000",
    assessingBody: "CPA Australia / CAANZ",
    notes: "CSOL only (employer-sponsored). Not on MLTSSL — cannot access 189/190/491 independently.",
  },

  // ── EDUCATION (MLTSSL — verified) ────────────────────────────────────────
  {
    anzsco: "241111",
    title: "Early Childhood (Pre-primary) Teacher",
    skillLevel: 1,
    category: "Education",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $65,000–$90,000",
    assessingBody: "ACECQA (Australian Children's Education & Care Quality Authority)",
    notes: "Critical shortage in childcare and kindergarten settings nationally",
  },
  {
    anzsco: "241411",
    title: "Secondary School Teacher",
    skillLevel: 1,
    category: "Education",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $75,000–$110,000",
    assessingBody: "AITSL (Australian Institute for Teaching and School Leadership)",
    notes: "STEM subjects (Maths, Physics, IT, Science) in chronic shortage. Priority under MD105.",
  },
  {
    anzsco: "241511",
    title: "Special Education Teacher",
    skillLevel: 1,
    category: "Education",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $75,000–$108,000",
    assessingBody: "AITSL",
    notes: "Includes 241512 Teacher of Hearing Impaired, 241513 Teacher of Sight Impaired — all MLTSSL",
  },
  {
    anzsco: "242111",
    title: "University Lecturer",
    skillLevel: 1,
    category: "Education",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $100,000–$160,000",
    assessingBody: "VETASSESS",
    notes: "Exempt from age limit for 186 ENS (academic exemption)",
  },

  // ── ARCHITECTURE & SPATIAL SCIENCE (MLTSSL — verified) ───────────────────
  {
    anzsco: "232111",
    title: "Architect",
    skillLevel: 1,
    category: "Architecture & Spatial Science",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $90,000–$150,000",
    assessingBody: "AACA (Architects Accreditation Council of Australia)",
  },
  {
    anzsco: "232112",
    title: "Landscape Architect",
    skillLevel: 1,
    category: "Architecture & Spatial Science",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $85,000–$130,000",
    assessingBody: "VETASSESS",
  },
  {
    anzsco: "232212",
    title: "Surveyor",
    skillLevel: 1,
    category: "Architecture & Spatial Science",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $95,000–$145,000",
    assessingBody: "ISNSW / Surveyors Board of each state",
  },

  // ── SCIENCE & RESEARCH (MLTSSL — verified) ───────────────────────────────
  {
    anzsco: "234112",
    title: "Agricultural Scientist",
    skillLevel: 1,
    category: "Science & Research",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $85,000–$130,000",
    assessingBody: "VETASSESS",
  },
  {
    anzsco: "234211",
    title: "Chemist",
    skillLevel: 1,
    category: "Science & Research",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $85,000–$125,000",
    assessingBody: "VETASSESS",
  },
  {
    anzsco: "234513",
    title: "Biochemist",
    skillLevel: 1,
    category: "Science & Research",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $85,000–$130,000",
    assessingBody: "VETASSESS",
  },
  {
    anzsco: "234514",
    title: "Biotechnologist",
    skillLevel: 1,
    category: "Science & Research",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $90,000–$135,000",
    assessingBody: "VETASSESS",
  },
  {
    anzsco: "224113",
    title: "Statistician",
    skillLevel: 1,
    category: "Science & Research",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $95,000–$140,000",
    assessingBody: "VETASSESS",
  },

  // ── SOCIAL WORK & LEGAL ───────────────────────────────────────────────────
  {
    anzsco: "272511",
    title: "Social Worker",
    skillLevel: 1,
    category: "Social Work & Legal",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $75,000–$105,000",
    assessingBody: "AASW (Australian Association of Social Workers)",
    notes: "Priority processing under MD105. Shortage in NDIS, child protection and regional areas.",
  },
  {
    anzsco: "271311",
    title: "Solicitor",
    skillLevel: 1,
    category: "Social Work & Legal",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $90,000–$200,000",
    assessingBody: "VETASSESS / State Law Society",
    notes: "Overseas lawyers typically need to sit the LPAB exam or complete an LLM bridging program. Complex pathway.",
  },
  {
    anzsco: "271111",
    title: "Barrister",
    skillLevel: 1,
    category: "Social Work & Legal",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID"],
    medianSalary: "AUD $150,000–$500,000+",
    assessingBody: "VETASSESS",
    notes: "Admission to the Bar requires local legal qualifications or assessment. Very complex for overseas practitioners.",
  },

  // ── TRADES — ELECTRICAL & PLUMBING (ALL MLTSSL — VERIFIED) ───────────────
  {
    anzsco: "341111",
    title: "Electrician (General)",
    skillLevel: 3,
    category: "Trades — Electrical & Plumbing",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID", "494"],
    medianSalary: "AUD $90,000–$130,000",
    assessingBody: "TRA (Trades Recognition Australia)",
    notes: "MLTSSL — full 189 access. One of the most in-demand trade occupations. Own business possible after state licensing.",
  },
  {
    anzsco: "341112",
    title: "Electrician (Special Class)",
    skillLevel: 3,
    category: "Trades — Electrical & Plumbing",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID", "494"],
    medianSalary: "AUD $100,000–$145,000",
    assessingBody: "TRA (Trades Recognition Australia)",
  },
  {
    anzsco: "341113",
    title: "Lift Mechanic",
    skillLevel: 3,
    category: "Trades — Electrical & Plumbing",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID", "494"],
    medianSalary: "AUD $100,000–$145,000",
    assessingBody: "TRA (Trades Recognition Australia)",
  },
  {
    anzsco: "342111",
    title: "Airconditioning & Refrigeration Mechanic",
    skillLevel: 3,
    category: "Trades — Electrical & Plumbing",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID", "494"],
    medianSalary: "AUD $85,000–$125,000",
    assessingBody: "TRA (Trades Recognition Australia)",
  },
  {
    anzsco: "334111",
    title: "Plumber (General)",
    skillLevel: 3,
    category: "Trades — Electrical & Plumbing",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID", "494"],
    medianSalary: "AUD $90,000–$140,000",
    assessingBody: "TRA (Trades Recognition Australia)",
    notes: "MLTSSL — full 189 access. Strong demand all states. Also includes 334112 Aircon/Mechanical Plumber, 334113 Drainer, 334114 Gasfitter, 334115 Roof Plumber — all MLTSSL.",
  },

  // ── TRADES — CONSTRUCTION (ALL MLTSSL — VERIFIED — corrected from STSOL/ROL) ─
  {
    anzsco: "331111",
    title: "Bricklayer",
    skillLevel: 3,
    category: "Trades — Construction",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID", "494"],
    medianSalary: "AUD $75,000–$115,000",
    assessingBody: "TRA (Trades Recognition Australia)",
    notes: "MLTSSL — verified. Can access Subclass 189 with sufficient points. Often misclassified as ROL-only.",
  },
  {
    anzsco: "331112",
    title: "Stonemason",
    skillLevel: 3,
    category: "Trades — Construction",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID", "494"],
    medianSalary: "AUD $75,000–$115,000",
    assessingBody: "TRA (Trades Recognition Australia)",
  },
  {
    anzsco: "331211",
    title: "Carpenter and Joiner",
    skillLevel: 3,
    category: "Trades — Construction",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID", "494"],
    medianSalary: "AUD $75,000–$115,000",
    assessingBody: "TRA (Trades Recognition Australia)",
    notes: "MLTSSL — verified. 331212 Carpenter and 331213 Joiner are also separately on MLTSSL.",
  },
  {
    anzsco: "332211",
    title: "Painter (Buildings)",
    skillLevel: 3,
    category: "Trades — Construction",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID", "494"],
    medianSalary: "AUD $70,000–$105,000",
    assessingBody: "TRA (Trades Recognition Australia)",
    notes: "MLTSSL — full 189 access",
  },
  {
    anzsco: "333111",
    title: "Glazier",
    skillLevel: 3,
    category: "Trades — Construction",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID", "494"],
    medianSalary: "AUD $70,000–$105,000",
    assessingBody: "TRA (Trades Recognition Australia)",
  },
  {
    anzsco: "333211",
    title: "Plasterer (Wall and Ceiling)",
    skillLevel: 3,
    category: "Trades — Construction",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID", "494"],
    medianSalary: "AUD $72,000–$110,000",
    assessingBody: "TRA (Trades Recognition Australia)",
    notes: "Also includes 333212 Renderer (Solid Plaster) — MLTSSL",
  },
  {
    anzsco: "333411",
    title: "Wall and Floor Tiler",
    skillLevel: 3,
    category: "Trades — Construction",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID", "494"],
    medianSalary: "AUD $72,000–$110,000",
    assessingBody: "TRA (Trades Recognition Australia)",
  },

  // ── TRADES — METAL & AUTOMOTIVE (ALL MLTSSL — VERIFIED) ──────────────────
  {
    anzsco: "321211",
    title: "Motor Mechanic (General)",
    skillLevel: 3,
    category: "Trades — Automotive & Metal",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID", "494"],
    medianSalary: "AUD $70,000–$100,000",
    assessingBody: "TRA (Trades Recognition Australia)",
    notes: "MLTSSL — verified. Often mistakenly listed as STSOL-only. CAN access Subclass 189. Also 321111 Automotive Electrician, 321212 Diesel Mechanic, 321213 Motorcycle Mechanic — all MLTSSL.",
  },
  {
    anzsco: "322311",
    title: "Metal Fabricator",
    skillLevel: 3,
    category: "Trades — Automotive & Metal",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID", "494"],
    medianSalary: "AUD $80,000–$120,000",
    assessingBody: "TRA (Trades Recognition Australia)",
  },
  {
    anzsco: "322313",
    title: "Welder (First Class)",
    skillLevel: 3,
    category: "Trades — Automotive & Metal",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID", "494"],
    medianSalary: "AUD $80,000–$120,000",
    assessingBody: "TRA (Trades Recognition Australia)",
    notes: "MLTSSL — verified. CAN access 189. Also 322312 Pressure Welder, 322211 Sheetmetal Worker — all MLTSSL.",
  },
  {
    anzsco: "323211",
    title: "Fitter (General)",
    skillLevel: 3,
    category: "Trades — Automotive & Metal",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID", "494"],
    medianSalary: "AUD $85,000–$125,000",
    assessingBody: "TRA (Trades Recognition Australia)",
    notes: "Also 323212 Fitter and Turner, 323213 Fitter-Welder, 323214 Metal Machinist (First Class) — all MLTSSL",
  },
  {
    anzsco: "324111",
    title: "Panelbeater",
    skillLevel: 3,
    category: "Trades — Automotive & Metal",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID", "494"],
    medianSalary: "AUD $70,000–$105,000",
    assessingBody: "TRA (Trades Recognition Australia)",
  },

  // ── HOSPITALITY — CHEF (MLTSSL) / COOK (STSOL) ───────────────────────────
  {
    anzsco: "351311",
    title: "Chef",
    skillLevel: 3,
    category: "Hospitality & Culinary",
    lists: ["MLTSSL", "CSOL"],
    visaAccess: ["189", "190", "491", "186", "482-SID", "494"],
    medianSalary: "AUD $65,000–$100,000",
    assessingBody: "TRA (Trades Recognition Australia)",
    notes: "MLTSSL — full 189 access. 3,920 PR grants nationally in 2025 — 160% year-on-year increase! #1 nationally by volume. 1,940 grants in NSW alone.",
  },
  {
    anzsco: "351411",
    title: "Cook",
    skillLevel: 3,
    category: "Hospitality & Culinary",
    lists: ["STSOL", "CSOL"],
    visaAccess: ["190", "491", "482-SID"],
    medianSalary: "AUD $55,000–$80,000",
    assessingBody: "TRA (Trades Recognition Australia)",
    notes: "IMPORTANT: Cook (351411) is STSOL — NOT eligible for 189. Chef (351311) is MLTSSL — eligible for 189. Ensure correct ANZSCO assessed by TRA.",
  },

  // ── COMMUNITY & PERSONAL SERVICES (CSOL only — new from Dec 2024) ─────────
  {
    anzsco: "411112",
    title: "Intensive Care Ambulance Paramedic",
    skillLevel: 2,
    category: "Community & Emergency Services",
    lists: ["CSOL"],
    visaAccess: ["482-SID", "186"],
    medianSalary: "AUD $80,000–$115,000",
    assessingBody: "VETASSESS",
    notes: "CSOL only (from Dec 2024). Not on MLTSSL — employer-sponsored SID/186 only.",
  },
  {
    anzsco: "411211",
    title: "Dental Hygienist",
    skillLevel: 2,
    category: "Community & Emergency Services",
    lists: ["CSOL"],
    visaAccess: ["482-SID", "186"],
    medianSalary: "AUD $75,000–$105,000",
    assessingBody: "Dental Board of Australia",
    notes: "CSOL only — employer-sponsored pathway",
  },
  {
    anzsco: "411411",
    title: "Enrolled Nurse",
    skillLevel: 2,
    category: "Community & Emergency Services",
    lists: ["CSOL"],
    visaAccess: ["482-SID", "186"],
    medianSalary: "AUD $60,000–$80,000",
    assessingBody: "ANMAC",
    notes: "CSOL only (Skill Level 2 — Diploma). Employer-sponsored only. Not on MLTSSL (which requires Registered Nurse).",
  },
];

// ── Category list ─────────────────────────────────────────────────────────────

export const occupationCategories = [
  "All",
  "ICT & Technology",
  "Engineering",
  "Healthcare — Doctors",
  "Healthcare — Nursing",
  "Healthcare — Allied Health",
  "Accounting & Finance",
  "Education",
  "Architecture & Spatial Science",
  "Science & Research",
  "Social Work & Legal",
  "Trades — Electrical & Plumbing",
  "Trades — Construction",
  "Trades — Automotive & Metal",
  "Hospitality & Culinary",
  "Community & Emergency Services",
];

// ── List metadata ─────────────────────────────────────────────────────────────

export const listDescriptions: Record<OccupationList, { label: string; color: string; description: string }> = {
  MLTSSL: {
    label: "MLTSSL",
    color: "bg-blue-100 text-blue-800",
    description: "Medium & Long-Term Strategic Skills List (212 occupations) — access to 189, 190, 491, 186, 482-SID",
  },
  STSOL: {
    label: "STSOL",
    color: "bg-amber-100 text-amber-800",
    description: "Short-Term Skilled Occupation List (215 occupations) — access to 190 and 491 only. NOT 189.",
  },
  ROL: {
    label: "ROL",
    color: "bg-teal-100 text-teal-800",
    description: "Regional Occupation List (77 occupations) — access to 491 and 494 (regional visas) only",
  },
  CSOL: {
    label: "CSOL",
    color: "bg-purple-100 text-purple-800",
    description: "Core Skills Occupation List (456 occ., from 7 Dec 2024) — Skills in Demand (SID) visa + 186 Direct Entry",
  },
};
