import type { BusinessFormData } from '@/types'

const DAYS_OF_WEEK = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'] as const

function defaultSchedule() {
  return DAYS_OF_WEEK.map(day => ({
    day,
    open: '9:00 am' as string | null,
    close: '5:00 pm' as string | null,
    closed: day === 'Sunday',
  }))
}

export function normalizeReportInput(data: Partial<BusinessFormData>): BusinessFormData {
  return {
    user_goal_mode: data.user_goal_mode ?? 'start_new',
    business_name: data.business_name?.trim() || 'Untitled business',
    business_concept: data.business_concept?.trim() || '',
    business_model_type: data.business_model_type ?? 'physical',
    state: data.state?.trim() || 'SA',
    suburb: data.suburb?.trim() || data.current_location_suburb?.trim() || '',
    postcode: data.postcode?.trim() || '',
    city: data.city?.trim() || '',
    lat: typeof data.lat === 'number' ? data.lat : null,
    lng: typeof data.lng === 'number' ? data.lng : null,
    suburb_profile: data.suburb_profile ?? null,
    radius_km: typeof data.radius_km === 'number' && data.radius_km > 0 ? data.radius_km : 3,
    business_type: data.business_type?.trim() || 'Other',
    business_type_other: data.business_type_other?.trim() || '',
    products_services: data.products_services?.trim() || '',
    avg_price_range: data.avg_price_range?.trim() || 'Custom quote',
    startup_budget: data.startup_budget ?? '',
    staff_count: typeof data.staff_count === 'number' ? data.staff_count : 1,
    operating_hours: data.operating_hours ?? '',
    operating_schedule: data.operating_schedule ?? defaultSchedule(),
    target_customers: data.target_customers ?? [],
    target_market: data.target_market ?? '',
    ad_budget_monthly: data.ad_budget_monthly ?? '',
    delivery_coverage: data.delivery_coverage ?? '',
    delivery_coverage_custom: data.delivery_coverage_custom ?? '',
    demand_zone_type: data.demand_zone_type ?? '',
    delivery_zone_importance: data.delivery_zone_importance ?? '',
    anchor_locations: data.anchor_locations ?? [],
    community_type: data.community_type ?? '',
    income_level: data.income_level ?? '',
    target_age_groups: data.target_age_groups ?? [],
    audience_types: data.audience_types ?? [],
    delivery_needed: data.delivery_needed ?? false,
    lunch_dinner_demand: data.lunch_dinner_demand ?? '',
    weekend_traffic_level: data.weekend_traffic_level ?? '',
    online_ordering_importance: data.online_ordering_importance ?? '',
    foot_traffic_expectation: data.foot_traffic_expectation ?? '',
    expected_revenue: data.expected_revenue ?? '',
    launch_timeline: data.launch_timeline ?? '',
    growth_goal: data.growth_goal ?? '',
    supply_model: data.supply_model ?? '',
    launch_inventory_assumption: data.launch_inventory_assumption ?? '',
    break_even_expectation: data.break_even_expectation ?? '',
    strategic_goals: data.strategic_goals ?? [],
    risk_tolerance: data.risk_tolerance ?? 'medium',
    current_monthly_revenue: data.current_monthly_revenue ?? '',
    target_monthly_revenue: data.target_monthly_revenue ?? '',
    current_challenges: data.current_challenges ?? [],
    current_customer_type: data.current_customer_type ?? '',
    existing_online_presence: data.existing_online_presence ?? '',
    expansion_goal: data.expansion_goal ?? '',
    growth_strategy_type: data.growth_strategy_type ?? '',
    new_suburb_expansion: data.new_suburb_expansion ?? false,
    delivery_expansion: data.delivery_expansion ?? false,
    business_age_band: data.business_age_band ?? '',
    years_in_business: typeof data.years_in_business === 'number' ? data.years_in_business : 1,
    current_location_suburb: data.current_location_suburb?.trim() || data.suburb?.trim() || '',
    premises_type: data.premises_type ?? '',
    current_team_size: typeof data.current_team_size === 'number' ? data.current_team_size : 2,
    average_daily_customers: typeof data.average_daily_customers === 'number' ? data.average_daily_customers : 20,
    repeat_customer_rate: typeof data.repeat_customer_rate === 'number' ? data.repeat_customer_rate : 25,
    average_basket_value: data.average_basket_value ?? '',
    best_selling_offer_price: data.best_selling_offer_price ?? '',
    premium_upsell_price: data.premium_upsell_price ?? '',
    monthly_fixed_costs: data.monthly_fixed_costs ?? '',
    monthly_staff_costs: data.monthly_staff_costs ?? '',
    average_gross_margin: typeof data.average_gross_margin === 'number' ? data.average_gross_margin : 45,
    best_selling_products: data.best_selling_products ?? [],
    worst_performing_products: data.worst_performing_products ?? [],
    busiest_trading_days: data.busiest_trading_days ?? [],
    quietest_trading_days: data.quietest_trading_days ?? [],
    best_traffic_channels: data.best_traffic_channels ?? [],
    best_converting_offers: data.best_converting_offers ?? [],
    lead_sources: data.lead_sources ?? [],
    peak_enquiry_periods: data.peak_enquiry_periods ?? [],
    strongest_acquisition_channels: data.strongest_acquisition_channels ?? [],
    average_google_rating: data.average_google_rating ?? '',
    google_review_count: typeof data.google_review_count === 'number' ? data.google_review_count : 0,
    social_media_channels: data.social_media_channels ?? [],
    website_conversion_quality: data.website_conversion_quality ?? '',
    delivery_platform_usage: data.delivery_platform_usage ?? [],
    supplier_dependency_risk: data.supplier_dependency_risk ?? '',
    website_url: data.website_url ?? '',
    instagram_url: data.instagram_url ?? '',
    facebook_url: data.facebook_url ?? '',
    tiktok_url: data.tiktok_url ?? '',
    google_business_profile_url: data.google_business_profile_url ?? '',
    linkedin_url: data.linkedin_url ?? '',
    average_monthly_website_visitors: typeof data.average_monthly_website_visitors === 'number' ? data.average_monthly_website_visitors : 0,
    instagram_followers: typeof data.instagram_followers === 'number' ? data.instagram_followers : 0,
    average_post_engagement: typeof data.average_post_engagement === 'number' ? data.average_post_engagement : 0,
    average_weekly_enquiries: typeof data.average_weekly_enquiries === 'number' ? data.average_weekly_enquiries : 0,
    conversion_rate: typeof data.conversion_rate === 'number' ? data.conversion_rate : 0,
    delivery_order_percentage: typeof data.delivery_order_percentage === 'number' ? data.delivery_order_percentage : 0,
    walk_in_percentage: typeof data.walk_in_percentage === 'number' ? data.walk_in_percentage : 0,
    customer_lifetime_estimate: data.customer_lifetime_estimate ?? '',
  }
}
